default_language_version:
    python: python3.9
repos:
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: node
        require_serial: true
        pass_filenames: false
        additional_dependencies: ["pyright@1.1.321"]
