[tool.poetry]
name = "include-test"
version = "0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.9.*"

[tool.pyright]
include = ["empty_folder/"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
