name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.4.2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'

      - name: Install project dependencies
        run: poetry install --all-extras

      - uses: pre-commit/action@v3.0.0
        if: always()
